### ISSUE TITLE
Massive memory consumption on KIND

### ISSUE THREAD

**Issue by Dimcon** [bitpoke/wordpress-operator#101]
**What happened**:
After installing the operator and launching a DB the memory usage spiked to 13GB before any connections were made to the DB.
![image (4)](https://user-images.githubusercontent.com/7796596/178693425-5623783e-30b0-4ae9-bd15-8be3580ac758.png)
The memory usage is from MysqlD running inside a Kind k8s cluster on my local machine.
Here's a snapshot of the memory using prometheus within Lens
![image](https://user-images.githubusercontent.com/7796596/178694135-8c6b99e3-7e4e-4416-a7d0-69f6cadf6405.png)

**What you expected to happen**:
After installation the pod tends to consume negligible memory. Around 200MB at idle. Even after a few thousand rows are added we don't normally see more than 300MB memory usage within k8s.

**How to reproduce it (as minimally and precisely as possible)**:
Environment:
Fedora 35
Docker
Kind
Prometheus
Lens for monitoring

Set up Kubernetes IN Docker (KIND)
https://kind.sigs.k8s.io/
Install bitpoke mysql operator v0.6.2
Create the following DB:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myapp-mysql-secret
  namespace: myapp
type: Opaque
data:
  ROOT_PASSWORD: ****
  USER: ****
  PASSWORD: ****
  DATABASE: ****

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: myapp
  namespace: myapp
spec:
  replicas: 1
  secretName: myapp-mysql-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
```
Watch memory usage.
