### ISSUE TITLE
Not possible to configure ingress class

### ISSUE THREAD

**Issue by constin** [bitpoke/wordpress-operator#102]
Not possible to configure ingress class with annotations, code will delete this annotation. I don't know reason, but it's not flexible. For example GKE with https support enabled will  try to use https lb, but sometimes better use tcp  lbwith internal ingress.
https://github.com/bitpoke/wordpress-operator/blob/39f32a00478aef67b2286fcbf1788597d137ebc8/pkg/controller/wordpress/internal/sync/ingress.go#L103

Also ingress pathType hardcoded too.  I'd like to have ability to configure it self.

**Comment by ryanmrodriguez** [comment]
Not sure if it helps your case, but you can set it as a flag to the operator.

```yaml
    spec:
      containers:
      - name: wordpress-operator
        image: bitpoke/wordpress-operator:v.0.12.1
        imagePullPolicy: Always
        args:
          - --ingress-class
          - nginx
```
