### ISSUE TITLE
Wordpress debugging environment variables are completely ignored.

### ISSUE THREAD

**Issue by droslean** [bitpoke/wordpress-operator#110]
**What happened**:
My website is blank and I want to investigate why. I have already configured the debugging related env var, but it seems that are being ignored. 

**What you expected to happen**:
To output debugging logs

**How to reproduce it (as minimally and precisely as possible)**:
wp-config.php with 
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', true );
@ini_set( 'display_errors', 1 );
```

or 

```
apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: my-wordpress
  namespace: my-ns
spec:
....
  env:
  - name: WP_DEBUG
    value: "true"
  - name: WP_DEBUG_LOG
    value: "true"
......
  image: docker.io/bitpoke/wordpress-runtime:6.3.1

```
